name: Docker Image CI

on:
  push:
    branches: [ "main" ] # 或者您的主分支名称，例如 master
  # 允许手动触发
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # 使用当前目录作为构建上下文
          file: ./Dockerfile # 指定 Dockerfile 路径
          push: true # 推送镜像
          tags: |
            kl3x/mysql-mecab:latest
          # 启用构建缓存以加快后续构建速度 (可选)
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: kl3x/mysql-mecab # 确保这与上面 tags 中的仓库名称匹配
          readme: ./README.md # 指定要用作描述的 README 文件路径